# Generated by Django 6.0.4 on 2026-05-14 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='NexusTime', max_length=100)),
                ('org_name', models.CharField(default='University of Agriculture', max_length=100)),
                ('academic_term', models.CharField(default='Fall 2026', max_length=100)),
                ('break_start', models.TimeField(blank=True, help_text='Local time when a fixed break starts (HH:MM)', null=True)),
                ('break_end', models.TimeField(blank=True, help_text='Local time when a fixed break ends (HH:MM)', null=True)),
                ('max_daily_classes', models.IntegerField(default=6, help_text='Soft limit for classes per batch per day')),
                ('gap_penalty', models.FloatField(default=1.0, help_text='Weight for the gap-minimization objective')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
