# Generated by Django 6.0.5 on 2026-05-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetableconstraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableconstraint',
            name='break_end',
            field=models.TimeField(blank=True, help_text='Local time when a fixed break ends (HH:MM)', null=True),
        ),
        migrations.AlterField(
            model_name='timetableconstraint',
            name='break_start',
            field=models.TimeField(blank=True, help_text='Local time when a fixed break starts (HH:MM)', null=True),
        ),
        migrations.AlterField(
            model_name='timetableconstraint',
            name='gap_penalty',
            field=models.FloatField(default=1.0, help_text='Weight for the gap-minimization objective'),
        ),
        migrations.AlterField(
            model_name='timetableconstraint',
            name='max_daily_classes',
            field=models.IntegerField(blank=True, help_text='Soft limit for classes per batch per day', null=True),
        ),
    ]
