# Generated by Django 6.0.4 on 2026-05-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_systemconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to the institution logo', max_length=500, null=True),
        ),
    ]
