# Generated by Django 6.0.5 on 2026-05-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_systemconfiguration_logo_url'),
    ]

    def migrate_department_fk_to_m2m(apps, schema_editor):
        # copy department_id from timetable_course into the new m2m table
        connection = schema_editor.connection
        cursor = connection.cursor()
        # ensure the course table has department_id column
        try:
            desc = connection.introspection.get_table_description(cursor, 'timetable_course')
            cols = [d.name for d in desc]
        except Exception:
            cols = []

        if 'department_id' not in cols:
            return

        Course = apps.get_model('timetable', 'Course')
        Department = apps.get_model('timetable', 'Department')

        cursor.execute("SELECT id, department_id FROM timetable_course WHERE department_id IS NOT NULL")
        rows = cursor.fetchall()
        for course_id, dept_id in rows:
            try:
                c = Course.objects.get(pk=course_id)
                d = Department.objects.get(pk=dept_id)
                c.department.add(d)
            except Exception:
                continue

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ManyToManyField(related_name='courses', to='timetable.department'),
        ),
        migrations.RunPython(migrate_department_fk_to_m2m, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
    ]
