# Generated by Django 6.0.5 on 2026-05-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_add_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleadjustmentrequest',
            name='requested_day',
            field=models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='', max_length=3),
        ),
    ]
