# Generated by Django 6.0.5 on 2026-05-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_remove_course_department_course_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduleentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='is_merged',
            field=models.BooleanField(default=False),
        ),
    ]
