# Generated by Django 6.0.5 on 2026-05-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_create_department_and_roomtype_models'),
        ('timetable', '0004_create_department_roomtype'),
    ]

    operations = [
    ]
