# Generated by Django 6.0.5 on 2026-05-14 21:18

import timetable.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_scheduleentry_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ManyToManyField(related_name='courses', to='timetable.department'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='working_days',
            field=models.JSONField(default=timetable.models.SystemConfiguration.default_working_days, help_text='List of working days abbreviation'),
        ),
    ]
