# Generated by Django 6.0.5 on 2026-05-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_merge_20260513_0820'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courseload',
            table='timetable_batch',
        ),
        migrations.AlterModelTable(
            name='faculty',
            table='timetable_teacher',
        ),
    ]
